### ISSUE TITLE
Problemas ao logar via Telegram

### ISSUE THREAD

**Issue by clcmo** [guildatech/GuildaEx#27]
Oi meninos,

Estava acessando o site e aí cliquei no "Entrar via Telegram". Na primeira tentativa, a API pediu para confirmar a integração e o fiz, na segunda tentativa, apareceu a seguinte mensagem: "Não foi possível autenticar".

Portanto, eu não consegui ver os conteúdos pós-login via Telegram, e estou abrindo essa issue.

**Comment by shamanime** [comment]
Obrigado por reportar :D

Foi necessário atualizar o token do bot.
